services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - backend
      - frontend

  frontend:
    container_name: frontend
    image: ${DOCKER_REGISTRY-}pokeapi-ui
    build:
      context: .
      dockerfile: /Dockerfile
    volumes:
    - .:/app
    - /app/node_modules
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    container_name: backend
    image: ${DOCKER_REGISTRY-}battleapi
    build:
      context: ..
      dockerfile: /PokeApi/BattleAPI/Dockerfile
    ports:
    - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=testPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ..:/app/PokeApi/BattleAPI 
    networks:
      - app_network

networks:
  app_network:
     driver: bridge